### PR TITLE
Fix Big Sur menu bar font color

### PR DESCRIPTION
**Pull request by MarlonJD**
On light theme, there was an issue about the font color. On light theme black color is really bad on Big Sur.

## Description

There was an issue about the font color when light theme was activated. So I changed font color and graph border color to white on light theme only on Big Sur.

So I changed these codes and I tested on my Mac.

## Related Issue
#250
Before:
image
After:
image

### CODE REVIEW

**Comment by D0miH** [comment]
As far as I can see you changed the font color to white if the current operating system is Big Sur, right?
After some research I found out that the font color in the menu bar depends on the wallpaper of the desktop. Meaning that if the wallpaper is dark, the menu bar theme gets light to have higher contrast. When the wallpaper is light, the theme of the menu bar is going to be dark.

I'm afraid just setting the font color to white if the current operating system is Big Sur won't do it.

I think  we would have to check if the `theme change`-callback was called without an actual change of the applied theme (As mentioned in https://stackoverflow.com/a/64525038). 
So I think the problem you experience is described in issue #229.
If you want you can change the code and try if you can detect the menu-bar-theme-change by observing the theme value in the callback function.

**Comment by MarlonJD** [comment]
Hmm i think you're right. I didn't realize wallpaper related menu bar colour. Maybe we can create button on dark or light font color on settings. But I'll research about the changing it automatically

**Comment by naveenyadav15** [comment]
This is the same issue I'm facing. Please update the code or give an option in the setting to change the color.

**Comment by dstamen** [comment]
any chance to commit/merge this?

**Comment by MarlonJD** [comment]
This is not production ready, macos bar background is changing with the wallpaper, so I couldn't fix the issue yet. If you got idea about the issue please inform

**Pull request closed without merging**
