### PR TITLE
Fix MacOS Big Sur Dark/Light theme font/border color issue

### PR DESCRIPTION
**Pull request by MarlonJD**
On light theme, there was an issue about the font color. On light theme black color is really bad on Big Sur.

## Description

There was an issue about the font color when light theme was activated. So I changed font color and graph border color to white on light theme only on Big Sur.

So I changed these codes and I tested on my Mac.

## Related Issue
Before:
image
After:
image

### CODE REVIEW

**Comment by ffreality** [comment]
such a nice fix !

**Comment by D0miH** [comment]
Hey @MarlonJD,
thanks for contributing to the project.
However, please don't merge your master in our master. 
Instead create a `bug-fix`-branch which is based on the current development branch as described [here](https://github.com/iglance/iGlance/blob/master/.github/CONTRIBUTING.md#getting-ready-for-development).

**Comment by MarlonJD** [comment]
Okay than. I'll do this and create pull request again

**Comment by MarlonJD** [comment]
I try to follow contributing rules. Please check #251

**Pull request closed without merging**
