### PR TITLE
Fixed incorrect condition for Low Battery notification

### PR DESCRIPTION
**Pull request by icy-meteor**
## Description
Low battery notification was getting triggered for the same value as set for Full Battery Notification value.

## Related Issue
Received low battery notification at 90% battery in default state.

### CODE REVIEW

**Review by D0miH — APPROVED** [review]

**Comment by D0miH** [comment]
Thanks a lot! 👍

**Comment by icy-meteor** [comment]
Happy to help @D0miH  💯  
If you don't mind, could you add "hacktoberfest-accepted" label to his PR. That way, it will get counted under my Hacktoberfest contribution towards planting a tree for the good :)

**Comment by D0miH** [comment]
Of course:)

**Comment by D0miH** [comment]
Done. Hope it registered correctly and got counted:)

**Comment by icy-meteor** [comment]
Affirm! It got counted, thanks a ton 👏🏼

**Pull request merged**
